#!/usr/bin/python
# -*- coding: UTF-8 -*-

globvar = 0

def set_globvar_to_one():
    global globvar
    globvar = 1
def print_globvar():
    print(globvar)    
set_globvar_to_one()
print  globvar 
print_globvar()